// Run once to create placeholder JSON files for all topics that don't exist yet
// These stubs ensure the app works immediately; run generate-questions.ts to expand to 5100 questions

import fs from "fs";
import path from "path";

const stubs: Record<string, object[]> = {
  "mean-median-mode": [
    {"id":"mmm-001","topic":"mean-median-mode","subtopic":"arithmetic mean","difficulty":"beginner","style":"conceptual","question":"What is the arithmetic mean of a dataset?","options":["The most frequently occurring value","The middle value when data is sorted","The sum of all values divided by the count of values","The difference between the maximum and minimum values"],"correctIndex":2,"explanation":"The arithmetic mean (average) sums all observations and divides by n. It represents the 'balancing point' of the distribution. Unlike the median, it is sensitive to extreme values — one very large or small number can substantially shift the mean."},
    {"id":"mmm-002","topic":"mean-median-mode","subtopic":"median","difficulty":"beginner","style":"conceptual","question":"How is the median found in a dataset with an even number of values?","options":["Take the value at position n/2","Average the two middle values","Take the maximum minus the minimum divided by 2","Use the most frequent value"],"correctIndex":1,"explanation":"With an even number of observations, there is no single middle value. The median is the average of the two central values after sorting. For example, in [2, 4, 6, 8], the median = (4+6)/2 = 5, even though 5 doesn't appear in the data."},
    {"id":"mmm-003","topic":"mean-median-mode","subtopic":"mode","difficulty":"beginner","style":"conceptual","question":"A dataset can have more than one mode. What is such a dataset called?","options":["Unimodal","Bimodal or multimodal","Uniform","Skewed"],"correctIndex":1,"explanation":"A dataset with two modes is bimodal; with more than two, it is multimodal. Multiple modes often indicate sub-populations within the data. The mode is the only measure of central tendency applicable to categorical (non-numeric) data."},
    {"id":"mmm-004","topic":"mean-median-mode","subtopic":"outlier resistance","difficulty":"intermediate","style":"misconception","question":"A researcher says: 'For salary data, the mean is the best measure of typical salary.' What is wrong?","options":["Nothing — mean is always the best measure","Salary data is typically right-skewed with outliers; the median better represents the typical worker","The mode should always be used for salary data","Mean and median are identical for salary data"],"correctIndex":1,"explanation":"Salary distributions are right-skewed — a few very high earners inflate the mean far above what most people earn. When Bill Gates walks into a bar, the mean wealth skyrockets but the median barely moves. The median is resistant to such outliers and better represents the 'typical' salary."},
    {"id":"mmm-005","topic":"mean-median-mode","subtopic":"weighted mean","difficulty":"intermediate","style":"calculation","question":"A student scores 80 on a test worth 30% and 90 on a test worth 70%. What is the weighted mean?","options":["85","87","83","88"],"correctIndex":1,"explanation":"Weighted mean = (80 × 0.30) + (90 × 0.70) = 24 + 63 = 87. The second test carries more weight, pulling the average closer to 90. Simple (unweighted) averages treat all items equally; weighted means account for differing importance."},
    {"id":"mmm-006","topic":"mean-median-mode","subtopic":"trimmed mean","difficulty":"intermediate","style":"conceptual","question":"What is the purpose of a trimmed mean?","options":["To make the mean equal the median","To remove a percentage of extreme values before computing the mean, reducing outlier influence","To calculate the mean for categorical variables","To weight each observation by its distance from the center"],"correctIndex":1,"explanation":"A trimmed mean (e.g., 10% trimmed) discards the lowest and highest 10% of values before averaging. It combines the outlier resistance of the median with the mathematical tractability of the mean. Olympic scoring often uses trimmed means to remove biased judges' scores."},
    {"id":"mmm-007","topic":"mean-median-mode","subtopic":"mean vs median comparison","difficulty":"beginner","style":"scenario","question":"House prices in a neighborhood are: $200K, $210K, $220K, $230K, $2,000K. Which measure best represents the typical house price?","options":["Mean: $572K","Median: $220K","Mode: there is no mode","Range: $1,800K"],"correctIndex":1,"explanation":"The $2M mansion is an outlier that pulls the mean to $572K, far above what most houses cost. The median ($220K) is unaffected by this extreme value and better represents what a typical buyer would pay. Always check for outliers before choosing mean vs. median."},
    {"id":"mmm-008","topic":"mean-median-mode","subtopic":"geometric mean","difficulty":"advanced","style":"conceptual","question":"When is the geometric mean preferred over the arithmetic mean?","options":["When data is normally distributed","When working with rates of change, ratios, or multiplicative processes","When the dataset has no outliers","When comparing two datasets of different sizes"],"correctIndex":1,"explanation":"The geometric mean (nth root of the product of n values) is appropriate for data involving multiplication or exponential growth — investment returns, bacterial growth rates, or inflation. If a stock grows 50% one year and falls 50% the next, the arithmetic mean of 0% is misleading; the geometric mean correctly shows a net loss."},
    {"id":"mmm-009","topic":"mean-median-mode","subtopic":"mean of grouped data","difficulty":"intermediate","style":"calculation","question":"For grouped data with bin [10-20) containing 5 values and bin [20-30) containing 3 values, the estimated mean uses midpoints 15 and 25. What is the estimated mean?","options":["18.75","20","17.5","22.5"],"correctIndex":0,"explanation":"Estimated mean = (15×5 + 25×3) / (5+3) = (75+75)/8 = 150/8 = 18.75. When raw data is unavailable but bins and frequencies are known, we approximate by treating all values in a bin as if they equal the bin's midpoint. This is standard practice with frequency tables."},
    {"id":"mmm-010","topic":"mean-median-mode","subtopic":"no mode","difficulty":"beginner","style":"conceptual","question":"A dataset where every value appears exactly once has:","options":["A mode equal to the mean","No mode","A mode equal to the median","Multiple modes"],"correctIndex":1,"explanation":"The mode is the value that appears most frequently. When every value occurs exactly once, there is no value that appears more than any other, so there is no mode (or we say all values are the mode, depending on convention). Mode is most useful for categorical or discrete data with repeated values."},
    {"id":"mmm-011","topic":"mean-median-mode","subtopic":"effect of adding a constant","difficulty":"intermediate","style":"calculation","question":"If 5 is added to every value in a dataset, what happens to the mean, median, and mode?","options":["Only the mean increases by 5","All three increase by exactly 5","Only the mode increases by 5","None change because they measure relative position"],"correctIndex":1,"explanation":"Adding a constant to every observation shifts all values equally, so the mean, median, and mode all shift by that same constant. This is a linear transformation. Subtracting 5 would decrease all three by 5; multiplying by a constant would multiply all three by that constant."},
    {"id":"mmm-012","topic":"mean-median-mode","subtopic":"mean of sampling distribution","difficulty":"advanced","style":"conceptual","question":"The mean of the sampling distribution of sample means equals:","options":["The sample standard deviation","The population mean μ","The sample mean x̄","The standard error"],"correctIndex":1,"explanation":"By the Central Limit Theorem, the sampling distribution of x̄ is centered at the population mean μ. This means the sample mean is an unbiased estimator of μ — on average across many samples, x̄ = μ. This unbiasedness is one reason the mean is so important in statistics."},
    {"id":"mmm-013","topic":"mean-median-mode","subtopic":"nominal data","difficulty":"beginner","style":"conceptual","question":"For nominal (categorical) data like eye color, which measure of central tendency is appropriate?","options":["Mean","Median","Mode","All three are equally appropriate"],"correctIndex":2,"explanation":"You cannot compute a mean or median for categories like 'blue, brown, green' — there's no numerical order or sum. Only the mode (most common category) is meaningful. This is why mode is the sole measure of central tendency applicable to all data types."},
    {"id":"mmm-014","topic":"mean-median-mode","subtopic":"mean sensitivity","difficulty":"intermediate","style":"scenario","question":"A quality control manager finds that removing one defective measurement changed the mean from 45.2 to 44.1 for a dataset of 20 observations. The removed value was approximately:","options":["22","43.9","67.1","1"],"correctIndex":2,"explanation":"Total before removal = 45.2×20 = 904. Total after removal = 44.1×19 = 837.9. Removed value = 904 − 837.9 = 66.1 ≈ 67.1. This illustrates how a single extreme value can substantially alter the mean, demonstrating its sensitivity to outliers."},
    {"id":"mmm-015","topic":"mean-median-mode","subtopic":"median for ordinal data","difficulty":"intermediate","style":"conceptual","question":"Survey responses are: Strongly Disagree, Disagree, Neutral, Agree, Strongly Agree. Why is the median more appropriate than the mean here?","options":["Median is always better than the mean","The responses have a natural order but equal spacing between categories cannot be assumed","Survey data always follows a normal distribution","Mean cannot be computed for data with 5 categories"],"correctIndex":1,"explanation":"Ordinal data has meaningful order but unknown interval widths — the 'distance' from Disagree to Neutral may not equal Neutral to Agree. Computing a mean requires equal spacing between numeric values. The median uses only rank information, making it appropriate for ordinal scales."},
    {"id":"mmm-016","topic":"mean-median-mode","subtopic":"harmonic mean","difficulty":"advanced","style":"calculation","question":"A car travels 60 mph for 1 hour and 30 mph for 1 hour. What is the average speed?","options":["45 mph (arithmetic mean)","40 mph (harmonic mean)","36 mph","50 mph"],"correctIndex":0,"explanation":"When traveling for equal TIME (not distance), arithmetic mean applies: (60+30)/2 = 45 mph. The harmonic mean applies when traveling equal DISTANCES. Since the car travels for equal times here, total distance = 60+30 = 90 miles, total time = 2 hours, average speed = 45 mph."},
    {"id":"mmm-017","topic":"mean-median-mode","subtopic":"mean vs median relationship","difficulty":"intermediate","style":"interpretation","question":"A dataset reports mean income = $65,000 and median income = $48,000. What can you infer?","options":["The data is approximately symmetric","The distribution is left-skewed","The distribution is right-skewed with high-income outliers pulling the mean up","Mean and median cannot differ by this much; there must be an error"],"correctIndex":2,"explanation":"Mean > median indicates right skew — high-income earners pull the mean above the median. The median ($48K) better represents what the 'typical' person earns. This is exactly the pattern seen in real household income data, which is why economists often report median household income."},
    {"id":"mmm-018","topic":"mean-median-mode","subtopic":"mean of binary data","difficulty":"intermediate","style":"calculation","question":"In a class of 30 students, 18 passed an exam. What is the mean of the binary pass/fail variable (1=pass, 0=fail)?","options":["0.5","0.6","18","0.4"],"correctIndex":1,"explanation":"Mean of binary (0/1) data = number of 1s / n = 18/30 = 0.6. The mean of a binary variable equals the proportion of 1s. This elegant property is why logistic regression predicts P(Y=1) as a mean — the expected value of a Bernoulli variable equals its probability."},
    {"id":"mmm-019","topic":"mean-median-mode","subtopic":"median position formula","difficulty":"beginner","style":"calculation","question":"For a sorted dataset of 15 values, the median is located at which position?","options":["Position 7","Position 8","Position 7.5","Position 15"],"correctIndex":1,"explanation":"Median position = (n+1)/2 = (15+1)/2 = 8. So the median is the 8th value in the sorted list. For even n, position = n/2 and (n/2)+1, then average those two values. Always sort the data first — median of unsorted data is meaningless."},
    {"id":"mmm-020","topic":"mean-median-mode","subtopic":"effect of multiplication","difficulty":"intermediate","style":"calculation","question":"If every value in a dataset is multiplied by 3, what happens to the mean?","options":["It stays the same","It increases by 3","It triples","It increases by the square root of 3"],"correctIndex":2,"explanation":"Multiplying each xᵢ by c multiplies the sum by c, and sum/n also multiplies by c. So the new mean = c × old mean. Similarly, the standard deviation multiplies by c (not c²). This is the scaling property of linear transformations."},
    {"id":"mmm-021","topic":"mean-median-mode","subtopic":"when mode is most useful","difficulty":"beginner","style":"scenario","question":"A shoe store wants to know which shoe size to stock most heavily. Which measure of central tendency is most useful?","options":["Mean — it uses all data","Median — it is resistant to outliers","Mode — it identifies the most common size purchased","Geometric mean — it handles skewed data"],"correctIndex":2,"explanation":"For stocking decisions, the most frequently purchased size (mode) is what matters, not an average. You can't stock 'size 9.7' shoes. Mode is ideal whenever you need the most common or popular category — product decisions, survey analysis, inventory planning."},
    {"id":"mmm-022","topic":"mean-median-mode","subtopic":"combining group means","difficulty":"advanced","style":"calculation","question":"Group A (n=10) has mean 20; Group B (n=30) has mean 40. What is the combined mean?","options":["30 (simple average)","35 (weighted average)","25","40"],"correctIndex":1,"explanation":"Combined mean = (n_A × mean_A + n_B × mean_B) / (n_A + n_B) = (10×20 + 30×40)/40 = (200+1200)/40 = 1400/40 = 35. Simply averaging the two means ignores group sizes. Group B has 3× the observations, so it gets 3× the weight."},
    {"id":"mmm-023","topic":"mean-median-mode","subtopic":"median of odd vs even","difficulty":"beginner","style":"misconception","question":"A student calculates the median of [3, 7, 9, 15] as 9. What mistake did they make?","options":["They forgot to sort the data","They should have averaged the two middle values: (7+9)/2 = 8","They used the wrong formula for odd-count data","The median is actually 15"],"correctIndex":1,"explanation":"For even-count datasets, the median is the average of the two middle values. Here, the two middle values are 7 and 9, so median = (7+9)/2 = 8. The student took only the upper middle value (9) instead of averaging both middle values."},
    {"id":"mmm-024","topic":"mean-median-mode","subtopic":"data without variation","difficulty":"beginner","style":"conceptual","question":"A dataset contains the values [7, 7, 7, 7, 7]. What is true about the mean, median, and mode?","options":["All three equal 7","Mean = 7, but median and mode are undefined","Mean is undefined because there is no variation","Only the mode is 7; mean and median require variation"],"correctIndex":0,"explanation":"When all values are identical, mean = median = mode = that value. There's nothing unusual or undefined here — mean is 35/5=7, median is the 3rd value=7, mode is 7 (appears 5 times). Zero variance doesn't prevent calculation of central tendency."},
    {"id":"mmm-025","topic":"mean-median-mode","subtopic":"robustness","difficulty":"intermediate","style":"conceptual","question":"Which measure of central tendency is most robust to extreme outliers?","options":["Arithmetic mean","Weighted mean","Median","Mode"],"correctIndex":2,"explanation":"Robustness means the statistic is unaffected by outliers. The median only considers rank order — adding one extremely large value to a dataset doesn't change the median (only shifts values above it). The mean uses all values' magnitudes, making it non-robust. The mode is context-dependent."}
  ],
  "variance-standard-deviation": [
    {"id":"var-001","topic":"variance-standard-deviation","subtopic":"variance definition","difficulty":"beginner","style":"conceptual","question":"What does variance measure in a dataset?","options":["The center of the data","The average squared deviation from the mean","The range between max and min","The most common value"],"correctIndex":1,"explanation":"Variance measures how spread out data is by computing the average of squared distances from the mean. Squaring serves two purposes: it removes negative signs so deviations don't cancel, and it penalizes large deviations more heavily than small ones."},
    {"id":"var-002","topic":"variance-standard-deviation","subtopic":"standard deviation","difficulty":"beginner","style":"conceptual","question":"Why is standard deviation often preferred over variance as a measure of spread?","options":["Standard deviation is always smaller than variance","Standard deviation is in the same units as the original data, making it interpretable","Standard deviation ignores outliers","Standard deviation can be negative, allowing directional comparison"],"correctIndex":1,"explanation":"Variance is in squared units (e.g., kg²), which is difficult to interpret. Taking the square root returns us to original units (kg), making standard deviation directly comparable to the mean and individual data values. This interpretability is why SD is more commonly reported."},
    {"id":"var-003","topic":"variance-standard-deviation","subtopic":"population vs sample variance","difficulty":"intermediate","style":"conceptual","question":"Why does the sample variance formula divide by (n-1) instead of n?","options":["It makes calculations easier","It corrects for the fact that sample variance with n would systematically underestimate population variance","It ensures variance is always positive","It is a historical convention with no mathematical basis"],"correctIndex":1,"explanation":"Sample data is typically more concentrated around the sample mean than around the true population mean. Dividing by n-1 (Bessel's correction) compensates for this bias, making sample variance an unbiased estimator of σ². The -1 reflects one degree of freedom lost by estimating the mean from the data."},
    {"id":"var-004","topic":"variance-standard-deviation","subtopic":"empirical rule","difficulty":"beginner","style":"conceptual","question":"In a normal distribution, approximately what percentage of data falls within 2 standard deviations of the mean?","options":["68%","95%","99.7%","50%"],"correctIndex":1,"explanation":"The empirical rule (68-95-99.7 rule): ~68% within 1 SD, ~95% within 2 SDs, ~99.7% within 3 SDs. These percentages only apply precisely to normal distributions but are useful approximations for bell-shaped data. '2 SDs' is the foundation for 95% confidence intervals."},
    {"id":"var-005","topic":"variance-standard-deviation","subtopic":"coefficient of variation","difficulty":"intermediate","style":"conceptual","question":"When comparing spread between datasets with different means, which measure is most appropriate?","options":["Standard deviation","Variance","Coefficient of variation (CV = SD/mean)","Range"],"correctIndex":2,"explanation":"Comparing SDs between datasets with different means is misleading — an SD of 10 is large for data with mean 15 but tiny for data with mean 1000. The CV expresses SD as a percentage of the mean, enabling fair comparison. CV = 5% is low variability regardless of scale."},
    {"id":"var-006","topic":"variance-standard-deviation","subtopic":"variance calculation","difficulty":"intermediate","style":"calculation","question":"For the dataset [2, 4, 4, 4, 5, 5, 7, 9], the mean is 5. What is the population variance?","options":["2","4","6","8"],"correctIndex":1,"explanation":"Deviations from mean 5: [-3,-1,-1,-1,0,0,2,4]. Squared deviations: [9,1,1,1,0,0,4,16]. Sum = 32. Variance = 32/8 = 4. (Note: sample variance = 32/7 ≈ 4.57.) This dataset is famous because its SD = √4 = 2, exactly, illustrating integer-friendly variance."},
    {"id":"var-007","topic":"variance-standard-deviation","subtopic":"effect of outliers on SD","difficulty":"intermediate","style":"scenario","question":"A dataset has SD = 3. One value of 200 is added to data centered around 10. The new SD will:","options":["Stay at 3","Decrease toward 0","Increase dramatically","Remain unchanged because 200 is just one point"],"correctIndex":2,"explanation":"Standard deviation is highly sensitive to outliers because it uses squared deviations. A value of 200 in data centered at 10 creates a massive squared deviation (190² = 36,100), dramatically inflating the variance and SD. This non-robustness is a key limitation of SD compared to IQR."},
    {"id":"var-008","topic":"variance-standard-deviation","subtopic":"zero variance","difficulty":"beginner","style":"conceptual","question":"What does a standard deviation of zero mean?","options":["The data has no mean","All values in the dataset are identical","The dataset is normally distributed","The data is binary"],"correctIndex":1,"explanation":"SD = 0 means every value equals the mean — there is no variation whatsoever. Every observation is identical. This occurs in artificial datasets or when a variable has been controlled to a constant. Such a variable carries no statistical information and cannot be used as a predictor."},
    {"id":"var-009","topic":"variance-standard-deviation","subtopic":"variance addition","difficulty":"advanced","style":"conceptual","question":"If X and Y are independent random variables, Var(X + Y) equals:","options":["Var(X) × Var(Y)","Var(X) + Var(Y)","(SD(X) + SD(Y))²","Var(X) - Var(Y)"],"correctIndex":1,"explanation":"Variances of independent random variables add. This is the key property underlying the standard error formula: Var(X̄) = Var(X)/n. Note that standard deviations do NOT simply add — you must add variances first, then take the square root."},
    {"id":"var-010","topic":"variance-standard-deviation","subtopic":"pooled standard deviation","difficulty":"advanced","style":"conceptual","question":"A pooled standard deviation in a two-sample t-test is used when:","options":["The two groups have very different means","The two populations are assumed to have equal variances","One group is much larger than the other","The data is non-normal"],"correctIndex":1,"explanation":"Pooled SD combines variance estimates from two groups, weighting by degrees of freedom, assuming the groups share a common σ. If this equal-variance assumption is violated, use Welch's t-test instead, which does not pool the variances. Levene's test can check the assumption."},
    {"id":"var-011","topic":"variance-standard-deviation","subtopic":"interquartile range vs SD","difficulty":"intermediate","style":"conceptual","question":"When would the IQR be preferred over standard deviation as a measure of spread?","options":["When data is normally distributed","When the dataset contains outliers or is heavily skewed","When the sample size is large","When comparing datasets with different means"],"correctIndex":1,"explanation":"IQR uses only the middle 50% of data and is unaffected by extreme values. SD uses all data and is heavily influenced by outliers. For skewed distributions or data with outliers (income, reaction times), IQR gives a more representative picture of typical spread."},
    {"id":"var-012","topic":"variance-standard-deviation","subtopic":"standard error vs SD","difficulty":"intermediate","style":"misconception","question":"A researcher reports the 'standard deviation' when they mean to communicate uncertainty in the mean estimate. What should they report instead?","options":["Variance","Standard error (SE = SD/√n)","Range","Coefficient of variation"],"correctIndex":1,"explanation":"SD describes spread in the raw data; SE describes uncertainty in the estimated mean. As n increases, SE shrinks (√n in denominator) even if SD stays constant. Reporting SD when summarizing mean precision overstates uncertainty for large samples and understates it conceptually."},
    {"id":"var-013","topic":"variance-standard-deviation","subtopic":"scaling variance","difficulty":"intermediate","style":"calculation","question":"If all values in a dataset are multiplied by 4, what happens to the variance?","options":["Variance multiplies by 4","Variance multiplies by 16","Variance does not change","Variance multiplies by 2"],"correctIndex":1,"explanation":"Var(cX) = c² × Var(X). Multiplying by 4: new variance = 4² × old variance = 16 × old variance. SD multiplies by 4 (|c|), but variance multiplies by c². This is why variance units are squared — when scale changes by c, squared units change by c²."},
    {"id":"var-014","topic":"variance-standard-deviation","subtopic":"mean absolute deviation","difficulty":"advanced","style":"conceptual","question":"Mean Absolute Deviation (MAD) uses |xi - x̄| instead of (xi - x̄)². Why is variance (squared deviations) preferred mathematically?","options":["Squared deviations are easier to compute by hand","Squared functions are differentiable everywhere and have elegant mathematical properties that absolute values lack at zero","Variance always gives smaller values than MAD","Absolute deviations cannot be summed"],"correctIndex":1,"explanation":"The absolute value function has a kink at zero where it's non-differentiable, complicating calculus-based optimization. Squared deviations are smooth everywhere, enabling calculus (e.g., proving the mean minimizes squared deviations). This mathematical tractability is why variance underlies most classical statistics."},
    {"id":"var-015","topic":"variance-standard-deviation","subtopic":"z-score","difficulty":"beginner","style":"calculation","question":"A student scores 78 on a test with mean 70 and SD 8. What is their z-score?","options":["0.78","1","8","0.5"],"correctIndex":1,"explanation":"z = (x - μ) / σ = (78 - 70) / 8 = 8/8 = 1. A z-score of 1 means the student scored exactly 1 standard deviation above the mean. Z-scores standardize measurements onto a common scale, enabling comparison across different tests or measurements."},
    {"id":"var-016","topic":"variance-standard-deviation","subtopic":"variance interpretation","difficulty":"beginner","style":"interpretation","question":"Dataset A has variance 9; Dataset B has variance 100. What can you conclude?","options":["Dataset A has a higher mean","Dataset B is more spread out around its mean","Dataset A has more outliers","Nothing — variance doesn't measure spread"],"correctIndex":1,"explanation":"Higher variance = more spread around the mean. Dataset B's values deviate more from their mean on average (SD_B = 10, SD_A = 3). However, this comparison is only meaningful if both datasets are in the same units and on similar scales."},
    {"id":"var-017","topic":"variance-standard-deviation","subtopic":"degrees of freedom","difficulty":"advanced","style":"conceptual","question":"Why does calculating sample variance 'lose' one degree of freedom?","options":["Because one observation is always removed as an outlier","Because the deviations (xi - x̄) must sum to zero, constraining one value once the others are known","Because the formula requires at least 2 data points","Because standard deviation cannot be negative"],"correctIndex":1,"explanation":"The n deviations from the sample mean must sum to exactly zero (mathematical constraint). This means if you know n-1 deviations, the last one is determined — it carries no new information. We've 'used up' one degree of freedom estimating the mean, leaving n-1 free deviations."},
    {"id":"var-018","topic":"variance-standard-deviation","subtopic":"standard deviation rule of thumb","difficulty":"beginner","style":"scenario","question":"A manufacturing process produces bolts with mean diameter 10mm and SD 0.5mm. A bolt is 11.5mm. Is this unusual?","options":["No — 11.5mm is only 1.5mm from the mean","Yes — 11.5mm is 3 standard deviations above the mean, which is very rare","It depends on the sample size","Cannot determine without knowing the distribution"],"correctIndex":1,"explanation":"z = (11.5 - 10) / 0.5 = 3. By the empirical rule, only ~0.3% of a normal distribution lies beyond 3 SDs. A z-score of 3 is very unusual, suggesting this bolt might indicate a manufacturing problem worth investigating."},
    {"id":"var-019","topic":"variance-standard-deviation","subtopic":"variance of a constant","difficulty":"beginner","style":"calculation","question":"What is the variance of the constant 7 (a variable that always equals 7)?","options":["7","49","1","0"],"correctIndex":3,"explanation":"A constant has no variation — it's always the same value. Every deviation from the mean is 0-0=0, so the average squared deviation is 0. Var(c) = 0 for any constant c. This is the minimum possible variance; variance is always ≥ 0."},
    {"id":"var-020","topic":"variance-standard-deviation","subtopic":"range vs SD","difficulty":"beginner","style":"conceptual","question":"Why is standard deviation generally preferred over range as a measure of spread?","options":["Range is always larger than SD","Range uses all data points; SD only uses two","SD uses all data points; range only uses two extreme values and ignores all others","SD is always easier to compute"],"correctIndex":2,"explanation":"Range = max - min uses only two values and is extremely sensitive to a single outlier. SD incorporates every observation, giving a more complete picture of overall variability. Adding one outlier can double the range while barely changing the SD of a large dataset."},
    {"id":"var-021","topic":"variance-standard-deviation","subtopic":"SD and data comparison","difficulty":"intermediate","style":"scenario","question":"Stock A has returns with mean 8% and SD 2%. Stock B has mean 8% and SD 15%. Which is riskier and why?","options":["Stock A — it has less variation around the mean","Stock B — the SD measures risk; higher SD means more unpredictable returns","Both equal risk — they have the same mean","Cannot compare because they might have different distributions"],"correctIndex":1,"explanation":"In finance, standard deviation of returns is the standard measure of risk (volatility). Stock B's returns vary much more widely — they could be 23% or -7% frequently, while Stock A stays close to 8%. Same expected return with much higher variance means more risk per unit of expected return."},
    {"id":"var-022","topic":"variance-standard-deviation","subtopic":"transforming to z-scores","difficulty":"intermediate","style":"conceptual","question":"After converting a dataset to z-scores, the new distribution has mean ___ and SD ___.","options":["0 and 1","1 and 0","Same as original","Depends on sample size"],"correctIndex":0,"explanation":"Z-score standardization: z = (x - μ)/σ subtracts the mean (centering at 0) and divides by SD (scaling to unit variance). The resulting distribution always has mean 0, SD 1. This enables comparison across different measurement scales — a z-score of 2 is comparably rare regardless of what was measured."},
    {"id":"var-023","topic":"variance-standard-deviation","subtopic":"sum of squares","difficulty":"advanced","style":"conceptual","question":"In ANOVA, 'sum of squares' refers to:","options":["The sum of all squared data values","The sum of squared deviations from a group mean or grand mean","The squared sample size","The sum of squared means"],"correctIndex":1,"explanation":"SS = Σ(xi - x̄)². In ANOVA, total SS is partitioned into between-group SS (variation explained by group membership) and within-group SS (unexplained variation). The ratio of these — the F-statistic — tests whether group means differ beyond what chance variation would produce."},
    {"id":"var-024","topic":"variance-standard-deviation","subtopic":"relative spread","difficulty":"intermediate","style":"interpretation","question":"Reaction times have mean 400ms and SD 80ms. Heights have mean 170cm and SD 10cm. Which variable has relatively more spread?","options":["Reaction time (larger SD)","Height (smaller SD means more precision)","Reaction time (CV = 20%, height CV = 5.9%)","They are equal — both have one standard deviation"],"correctIndex":2,"explanation":"Comparing raw SDs across different scales is misleading. CV(reaction time) = 80/400 = 20%; CV(height) = 10/170 ≈ 5.9%. Reaction times have proportionally much more spread relative to their mean. The coefficient of variation normalizes spread by scale."},
    {"id":"var-025","topic":"variance-standard-deviation","subtopic":"variance and independence","difficulty":"advanced","style":"conceptual","question":"Var(X - Y) when X and Y are independent equals:","options":["Var(X) - Var(Y)","Var(X) + Var(Y)","Var(X) × Var(Y)","0"],"correctIndex":1,"explanation":"Var(X - Y) = Var(X) + Var(Y) when X and Y are independent. Variances always add — even for subtraction — because variance measures squared spread, which is always positive. This is why the standard error of a difference is √(SE₁² + SE₂²), not SE₁ - SE₂."}
  ]
};

const outDir = path.join(process.cwd(), "public", "questions");

for (const [topic, questions] of Object.entries(stubs)) {
  const filePath = path.join(outDir, `${topic}.json`);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, JSON.stringify(questions, null, 2));
    console.log(`Created stub: ${topic}.json (${questions.length} questions)`);
  }
}
